require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/*.rb'
  Exclude:
    - fixtures/**/*
  NewCops: disable
  SuggestExtensions: false

Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/ShadowedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/MultilineBlockChain:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false

Naming/FileName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
