name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu-ruby-${{ matrix.ruby-version }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Runs tests
        run: bundle exec rake test
